### ISSUE TITLE
Install vips on ci test

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#324]

**Comment by rosell-dk** [comment]
Tried the old shell script I used for travis ci. 
Building seems to have worked, but it failed installing the extension. 
https://github.com/rosell-dk/webp-convert/runs/4405804342?check_suite_focus=true

**Comment by rosell-dk** [comment]
We could look here for inspiration:
https://github.com/libvips/libvips/actions/runs/1062758054/workflow

**Comment by rosell-dk** [comment]
Ta-dah!
It was as easy as adding "vips" to the extensions for setup-php:

```
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: exif, mbstring, fileinfo, gd, vips
```
